version: '3.7'

services:
  frontend:
    build:
      context: ./react_app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./flask_server
    ports:
      - "5000:5000"
